"""create audit log table

Revision ID: 201a120145fd
Revises: a315a39b9797
Create Date: 2026-06-17 16:22:18.717235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201a120145fd'
down_revision = 'a315a39b9797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
