"""Add photo_source column

Revision ID: 648c21d366d9
Revises: 201a120145fd
Create Date: 2026-06-26 12:08:07.429183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648c21d366d9'
down_revision = '201a120145fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_source', sa.String(length=20), nullable=True, server_default='local'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('photo_source')

    # ### end Alembic commands ###
