"""Add cloudinary public id

Revision ID: 939e760c8d5d
Revises: 648c21d366d9
Create Date: 2026-06-30 11:04:08.986133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939e760c8d5d'
down_revision = '648c21d366d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_public_id')

    # ### end Alembic commands ###
