"""add photo column

Revision ID: a315a39b9797
Revises: 6682d15d6f05
Create Date: 2026-06-16 16:11:07.064350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a315a39b9797'
down_revision = '6682d15d6f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('employee', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [
        c["name"]
        for c in inspector.get_columns("employee")
    ]

    if "photo" not in columns:
        with op.batch_alter_table("employee") as batch_op:
            batch_op.add_column(
                sa.Column(
                    "photo",
                    sa.String(length=255),
                    nullable=True

                )
            )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
